---
title: "Pictures"
# description: |
#   some pictures
# pixture library from https://github.com/royfrancis/pixture
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
paths <- c(
  "images/engagement/eng1.jpg",
  "images/engagement/eng2.jpg",
  "images/engagement/eng3.jpg",
  "images/engagement/eng4.jpg",
  "images/engagement/eng5.jpg",
  "images/engagement/eng6.jpg",
  "images/engagement/eng7.jpg",
  "images/engagement/eng8.jpg",
  "images/engagement/eng9.jpg",
  "images/engagement/eng10.jpg",
  "images/engagement/eng11.jpg",
  "images/engagement/eng12.jpg",
  "images/engagement/eng13.jpg",
  "images/engagement/eng14.jpg",
  "images/engagement/eng15_cover.jpg",
  "images/engagement/eng16.jpg",
  "images/engagement/eng17.jpg",
  "images/engagement/eng18.jpg",
  "images/engagement/eng19.jpg",
  "images/engagement/eng20.jpg",
  "images/engagement/eng21.jpg",
  "images/engagement/eng22.jpg",
  "images/engagement/eng23.jpg",
  "images/engagement/eng24.jpg",
  
  "images/evie2.jpg",
  "images/evie1.jpg",
  "images/pippin.jpg"  

)

#library(pixture)
pixture::pixgallery(paths)
```
