---
title: "Wedding"
# description: |
#   some pictures
# pixture library from https://github.com/royfrancis/pixture
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


<!-- ```{r} -->
<!-- # Resize jpg for web -->
<!-- library(magick) -->
<!-- in_dir <- "C:/Users/Leslie/Desktop/wedding_pics/wedding" -->
<!-- out_dir <- "images/wedding" -->
<!-- dir.create(out_dir, recursive = TRUE, showWarnings = FALSE) -->

<!-- files <- list.files(in_dir, pattern = "(?i)\\.jpe?g$", full.names = TRUE) -->

<!-- for (f in files) { -->
<!--   img <- image_read(f) -->
<!--   img <- image_orient(img) # Honor camera rotation -->
<!--   img <- image_scale(img, "1600x1600") # Shrink to fit box, keep aspect ratio -->
<!--   image_write(img, -->
<!--               path = file.path(out_dir, basename(f)), -->
<!--               format = "jpeg", -->
<!--               quality = 82) -->
<!-- } -->
<!-- ``` -->


```{r}
paths <- list.files(
  "images/wedding",
  pattern = "\\.jpe?g$",
  full.names = TRUE,
  ignore.case = TRUE
)

#library(pixture)
pixture::pixgallery(paths)
```
